### ISSUE TITLE
running in background

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/AFQ-Browser#109]
@richford @arokem If I point my browser to localhost:8080 I get an afq browser instance even if I don't launch one with afqbrowser-run. Does this mean that it is running in the background? I also can't seem to update data now and it only shows the example data even if I launch a new instance.

**Comment by arokem** [comment]
I don't see this when I use a keyboard interrupt (ctrl-c) to stop it.

I think this might be because of the way that the webserver gets
initialized here:
https://github.com/yeatmanlab/AFQ-Browser/blob/master/afqbrowser/browser.py#L167-L170

Note the "serve_forever" part. I think it keeps running in the background
"forever" unless you use the keyboard interrupt.

We should fix this, but for the time being, you should be able to bypass
this by passing a port argument. For example:

    afqbrowser-run -p 8081

**Comment by jyeatman** [comment]
afqbrowser-run -p 8081 works for me

But I think this confirms that I still have a version running on 8080 in the background and this persists even after I restart my computer
